### ISSUE TITLE
It doesn't work with https://perso.crans.org/besson/notebooks/agreg/Mediane_des_medianes__selection_en_temps_lineaire.html

### ISSUE THREAD

**Issue by ArnaudBegyn** [fomightez/back_to_ipynb#1]
It doesn't work with https://perso.crans.org/besson/notebooks/agreg/Mediane_des_medianes__selection_en_temps_lineaire.html

Thanks for your help

**Comment by fomightez** [comment]
It does work with that link. You may have not realized though you needed to use the updated tags that were detailed in the penultimate code cell [there](https://nbviewer.org/github/fomightez/back_to_ipynb/blob/8edeba7071c30f2a5abe48cb19592f85b2e935ce/back_to_the_ipynb_demo.ipynb) (way down near the bottom, the code cell that has 'In [10]' next to it). 

I think the old tags are probably mostly gone now and so what I've done is move the use of the current tags to the featured top example and referenced a source of the code that works that has the old tags (actually just an old version of the featured notebook). This way things should work for most people because most will have current things. Then those with old stuff can use the old version.

It makes the end of the notebook clunky now because things should work already with the featured code but maybe eventually, I clean that up to be clearer again.

-----

-----



Here is the code to use in the first cell of the featured notebook to run the process on yours:

```python
t = '''from bs4 import BeautifulSoup
import json
import urllib.request
url = 'https://perso.crans.org/besson/notebooks/agreg/Mediane_des_medianes__selection_en_temps_lineaire.html'
response = urllib.request.urlopen(url)
#  for local html file
# response = open("/Users/note/jupyter/notebook.html")
text = response.read()

soup = BeautifulSoup(text, 'lxml')
# see some of the html
print(soup.div)
dictionary = {'nbformat': 4, 'nbformat_minor': 1, 'cells': [], 'metadata': {}}
for d in soup.findAll("div"):
    if 'class' in d.attrs.keys():
        for clas in d.attrs["class"]:
            if clas in ["jp-RenderedMarkdown", "jp-InputArea-editor"]:
                # code cell
                if clas == "jp-InputArea-editor":
                    cell = {}
                    cell['metadata'] = {}
                    #cell['outputs'] = []
                    cell['source'] = [d.get_text()]
                    cell['execution_count'] = None
                    cell['cell_type'] = 'code'
                    dictionary['cells'].append(cell)

                else:
                    cell = {}
                    cell['metadata'] = {}

                    cell['source'] = [d.decode_contents()]
                    cell['cell_type'] = 'markdown'
                    dictionary['cells'].append(cell)
open('notebook.ipynb', 'w').write(json.dumps(dictionary))
'''
%store t >back_to_the_ipynb_script.py
```


Then run the next two cells and `notebook.ipynb` produced should be what you seek.

**Comment by ArnaudBegyn** [comment]
thanks it works
